// Generated by Wrangler by running `wrangler types`

interface Env {
	JWT_SECRET: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_DATABASE_ID: string;
	CLOUDFLARE_D1_TOKEN: string;
	BUCKET: R2Bucket;
	DB: D1Database;
}
